/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geodesia.geometrica;

import javax.swing.JTextField;

/**
 *
 * @author LENOVO
 */
public class Panel extends javax.swing.JPanel {

    /**
     * Creates new form Panel
     */
    CalcularCoordenadas coordenadas=new CalcularCoordenadas(); 
    
    public Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        LGrados = new javax.swing.JTextField();
        texto2 = new javax.swing.JLabel();
        LSegundos = new javax.swing.JTextField();
        texto3 = new javax.swing.JLabel();
        LMinutos = new javax.swing.JTextField();
        texto4 = new javax.swing.JLabel();
        agregarLatitud = new javax.swing.JButton();
        texto5 = new javax.swing.JLabel();
        resultadoY = new javax.swing.JLabel();
        calcularY = new javax.swing.JButton();
        texto6 = new javax.swing.JLabel();
        resultadoZ = new javax.swing.JLabel();
        calcularZ = new javax.swing.JButton();
        prueba = new javax.swing.JTextField();

        titulo.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        titulo.setText("Geodesia Geomètrica");

        titulo1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        titulo1.setText("Calcular coordenadas y,z");

        texto1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        texto1.setText("Latitud Geodèsica");

        texto2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texto2.setText("º");

        texto3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texto3.setText("'");

        texto4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texto4.setText("\"");

        agregarLatitud.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        agregarLatitud.setText("Agregar Latitud");
        agregarLatitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarLatitudMouseClicked(evt);
            }
        });

        texto5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        texto5.setText("Y=");

        resultadoY.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        resultadoY.setText("resultado");

        calcularY.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        calcularY.setText("Calcular");

        texto6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        texto6.setText("Y=");

        resultadoZ.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        resultadoZ.setText("resultado");

        calcularZ.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        calcularZ.setText("Calcular");

        prueba.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(titulo1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(texto1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(texto2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(texto3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(texto4)
                                .addGap(18, 18, 18)
                                .addComponent(agregarLatitud))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(prueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(texto5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(resultadoY)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(calcularY)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(texto6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resultadoZ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(calcularZ)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto1)
                    .addComponent(LGrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto2)
                    .addComponent(LSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto3)
                    .addComponent(LMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto4)
                    .addComponent(agregarLatitud))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto5)
                    .addComponent(resultadoY)
                    .addComponent(calcularY)
                    .addComponent(texto6)
                    .addComponent(resultadoZ)
                    .addComponent(calcularZ))
                .addGap(33, 33, 33)
                .addComponent(prueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarLatitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarLatitudMouseClicked
       double valor1 = Double.parseDouble(LGrados.getText());
       coordenadas.grados=(double)valor1; 
       double valor2 = Double.parseDouble(LMinutos.getText());
       coordenadas.minutos=(double)valor2;
       double valor3 =Double.parseDouble(LSegundos.getText());
       coordenadas.segundos=(double)valor3;
       prueba.setText(String.valueOf(coordenadas.ConvertirGrados()));
    
    }//GEN-LAST:event_agregarLatitudMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LGrados;
    private javax.swing.JTextField LMinutos;
    private javax.swing.JTextField LSegundos;
    private javax.swing.JButton agregarLatitud;
    private javax.swing.JButton calcularY;
    private javax.swing.JButton calcularZ;
    private javax.swing.JTextField prueba;
    private javax.swing.JLabel resultadoY;
    private javax.swing.JLabel resultadoZ;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    private javax.swing.JLabel texto5;
    private javax.swing.JLabel texto6;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables
}
